### ISSUE TITLE
Requirements need to install before using pdf2img

### ISSUE THREAD

**Issue by khay** [fitraditya/node-pdf2img#10]
I just started using this to convert pdf to images, but currently I am having problem with this error.

	/bin/sh: identify: command not found
	child_process.js:508
	    throw err;
	    ^

	Error: Command failed: identify -format %n upload/2117c56efbd65908ae368201ec6517651468295928045.pdf
	/bin/sh: identify: command not found

I've installed xpdf, using node v4.4.7 and trying to use local pdf file. Is there any requirements like `imagemagick` ?

**Comment by khay** [comment]
Error `/bin/sh: identify` is fixed after I installed imagemagick. But still getting this error.

	child_process.js:508
	    throw err;
	    ^

	Error: Command failed: identify -format %n upload/8322faa89ed45c91c7f4f82172fdb5a21468383573114.pdf

**Comment by khay** [comment]
The problems are solved after I installed `ghostscript`. But still convert image is zero KB. I will figure out myself for this. Thanks.

**Comment by s1rd4v3** [comment]
@khay did you get the zero KB issue fixed? i have the same problem. thanks.

**Comment by marxys** [comment]
try to create a symbolic link from /usr/local/bin/gs => /usr/bin/gs or from /usr/bin/gs => /usr/local/bin/gs following which binary exists in your environment.

**Comment by LuciusFx** [comment]
@s1rd4v3 i've the same 0 kb output problem... u solved that?

**Comment by s1rd4v3** [comment]
@LuciusFx no i didn't get it working. i'm using https://www.npmjs.com/package/pdf-image instead. not perfect either, but fits my needs.
