### ISSUE TITLE
Command failed: identify

### ISSUE THREAD

**Issue by leonardo24** [fitraditya/node-pdf2img#18]
Hi, im gettin this error even when i try "matteocontrin" solution...

Uncaught Error: Command failed: identify -format %n C:/Users/Username/Desktop/prueba.pdf
"identify" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Can u help me?

**Comment by marxys** [comment]
My pull request #19 fix your problem.

**Comment by fitraditya** [comment]
Now this module only requires GraphicsMagick.
