### ISSUE TITLE
Image in output is 0 kb

### ISSUE THREAD

**Issue by LuciusFx** [fitraditya/node-pdf2img#21]
When i try to convert a pdf into a png or jpeg the result is an empty image but no errors in the console. Someone has the same problem or has a solution? thx.

**Comment by daudiihhdau** [comment]
I've got the same problem :-)

**Comment by hemants** [comment]
Faced same issue :(

**Comment by shanehandley** [comment]
Same issue

**Comment by SPlatten** [comment]
Same...after fixing the dependencies and installing ghostscript, I now get lots of empty png files and a console error:  proc.stdin.once('error', cb);

**Comment by fitraditya** [comment]
I updated this module to fix some issues. Now this module only requires GraphicsMagick.
Please check it out.
